name: automerge
on:
  schedule:
    - cron: '*/5 07-15 * * 4'
    - cron: '*/5 07-15 * * 1-3'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "SanjiKir/automerge-action@885776e702226145b3c872d6f85e291477d00c1e"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "ready-to-merge"
          MERGE_APROOVED_BY_REVIEWERS: "DmytryTkachenko, JakubTkadlacek, TkachenkoDmitry"