name: automerge
on:
  schedule:
    - cron: '0 08,16,18,20 * * 1-3'
    - cron:  '*/5 07-15 * * 4'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "ready-to-merge"
