name: automerge
on:
  schedule:
    - cron: '*/5 07-15 * * 4'
    - cron: '*/5 07-15 * * 1-3'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "SanjiKir/automerge-action@d1b10d45ec9b1874d5234fa0589dab40c32c540a"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "ready-to-merge"
          MERGE_APROOVED_BY_REVIEWERS: "DmytryTkachenko, JakubTkadlacek, TkachenkoDmitry"