name: automerge
on:
  schedule:
    - cron: '*/5 07-15 * * 4'
    - cron: '*/5 07-15 * * 1-3'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "SanjiKir/automerge-action@167e224c922f22e96e9002013fe20ae5b24f02ed"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "ready-to-merge"
          MERGE_APROOVED_BY_REVIEWERS:
            - DmytryTkachenko
            - JakubTkadlacek
            - Zhopa