name: automerge
on:
  schedule:
    - cron: '15 08,15 * * 1-4'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_REMOVE_LABELS: "ready-to-merge"
          MERGE_LABELS: "ready-to-merge"
